# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.17

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    # Path must conform to the Go Workspace requirements
    working_directory: /go/src/github.com/john-d-pelingo/godbot

    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go get -v golang.org/x/lint/golint
      - run: go get -v github.com/golangci/golangci-lint/cmd/golangci-lint

      - run: go vet -x ./...
      - run: golint -set_exit_status ./...
      - run: golangci-lint run --enable-all
      - run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - run: bash <(curl -s https://codecov.io/bash)
      - run: go build
