# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

workflows:
  version: 2
  test:
    jobs:
      - test-1.11
      - test-1.12
      - test-1.13

jobs:
  test-1.11: &test-template
    docker:
      # specify the version
      - image: circleci/golang:1.11

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    # Path must conform to the Go Workspace requirements
    working_directory: /go/src/github.com/john-d-pelingo/godbot

    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go get -v golang.org/x/lint/golint
      - run: go get -v github.com/golangci/golangci-lint/cmd/golangci-lint

      - run: go vet -x ./...
      - run: golint -set_exit_status ./...
      - run: golangci-lint run --enable-all
      - run: go test -v ./...
  test-1.12:
    <<: *test-template
    docker:
      - image: circleci/golang:1.12
  test-1.13:
    <<: *test-template
    docker:
      - image: circleci/golang:1.13
